### ISSUE TITLE
License

### ISSUE THREAD

**Issue by framarbon** [latture/pallas-solver#2]
Hi @latture 
Thanks for the great work.

Could you add a license to your repo?

**Comment by latture** [comment]
Yes, of course. I released it under the MIT license in the latest commit.

**Comment by framarbon** [comment]
Thanks @latture !

I checked the source files of the repo and all of them seem to have a BSD-2 license. 
Wouldn't it fit better to use the same license for the repo?

**Comment by latture** [comment]
BSD-2 and MIT are very similar (essentially identical), so I don't have a strong preference for one over the other. Happy to use BSD-2 if it's easier to use.

**Comment by latture** [comment]
BSD-2 license was added in [c38f1f1](https://github.com/latture/pallas-solver/commit/c38f1f1d04d93cf8f553bc7395e8ecd96202671a).
